import { readFile } from "node:fs/promises";
import type { IncomingMessage, ServerResponse } from "node:http";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = fileURLToPath(new URL(".", import.meta.url));
const AGENT_DIR = process.env.AGENT_DIR ? resolve(process.env.AGENT_DIR) : resolve(__dirname, "..", "..", "agent");
const ALLOWED_AGENT_FILES = new Set<string>(["agent.js", "package.json", "install.ps1", "uninstall.ps1", "icon.ico"]);
const BOOTSTRAP_DOWNLOAD_LIST = ["agent.js", "package.json", "install.ps1", "uninstall.ps1", "icon.ico"];
export function isInstallPath(pathname: string): boolean {
  return pathname === "/install/bootstrap.ps1" || pathname.startsWith("/install/agent/");
}
export async function handleInstall(req: IncomingMessage, res: ServerResponse, publicBase: string): Promise<void> {
  const url = new URL(req.url ?? "/", "http://x");
  const path = url.pathname;
  if (path === "/install/bootstrap.ps1") {
    return serveBootstrap(req, res, url, publicBase);
  }
  if (path.startsWith("/install/agent/")) {
    return serveAgentFile(req, res, path);
  }
  res.writeHead(404, {
    "Content-Type": "text/plain"
  }).end("Not found");
}
function serveBootstrap(_req: IncomingMessage, res: ServerResponse, url: URL, publicBase: string): void {
  const rawUser = url.searchParams.get("user") ?? "";
  const user = sanitizeUser(rawUser);
  if (!user) {
    res.writeHead(400, {
      "Content-Type": "text/plain; charset=utf-8"
    }).end("Missing or invalid ?user — expected /install/bootstrap.ps1?user=<pseudo>");
    return;
  }
  const safeBase = sanitizeBase(publicBase);
  const ps = renderBootstrap({
    user,
    serverBase: safeBase,
    files: BOOTSTRAP_DOWNLOAD_LIST
  });
  res.writeHead(200, {
    "Content-Type": "text/plain; charset=utf-8",
    "Cache-Control": "no-store",
    "Content-Disposition": `inline; filename="veadmin-agent-install.ps1"`
  });
  res.end(ps);
}
async function serveAgentFile(_req: IncomingMessage, res: ServerResponse, pathname: string): Promise<void> {
  const name = pathname.slice("/install/agent/".length);
  if (!ALLOWED_AGENT_FILES.has(name) || name.includes("/") || name.includes("\\")) {
    res.writeHead(404, {
      "Content-Type": "text/plain"
    }).end("Not found");
    return;
  }
  let data: Buffer;
  try {
    data = await readFile(join(AGENT_DIR, name));
  } catch {
    res.writeHead(404, {
      "Content-Type": "text/plain"
    }).end("Not found");
    return;
  }
  const mime = name.endsWith(".js") ? "application/javascript; charset=utf-8" : name.endsWith(".json") ? "application/json; charset=utf-8" : name.endsWith(".ps1") ? "text/plain; charset=utf-8" : name.endsWith(".ico") ? "image/x-icon" : "application/octet-stream";
  res.writeHead(200, {
    "Content-Type": mime,
    "Cache-Control": "public, max-age=300"
  });
  res.end(data);
}
function sanitizeUser(raw: string): string {
  return raw.trim().toLowerCase().replace(/[^a-z0-9._@-]/g, "");
}
function sanitizeBase(raw: string): string {
  const trimmed = raw.replace(/\/+$/, "");
  if (!/^https?:\/\/[a-zA-Z0-9.\-:/]+$/.test(trimmed)) {
    return "https://remote-control-cdqo.onrender.com";
  }
  return trimmed;
}
interface BootstrapInputs {
  user: string;
  serverBase: string;
  files: readonly string[];
}
function renderBootstrap({
  user,
  serverBase,
  files
}: BootstrapInputs): string {
  const fileList = files.map(f => `'${f}'`).join(", ");
  return `# VE Admin remote-support agent — auto-bootstrap installer.
# Generated by ${serverBase}/install/bootstrap.ps1 — do not save & re-use,
# always re-fetch so the latest agent build comes down.

$ErrorActionPreference = 'Stop'

$VEAdminUser   = '${user}'
$VEAdminServer = '${serverBase}'
$Files         = @(${fileList})

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  VE Admin agent — bootstrap" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ("  Pseudo : {0}" -f $VEAdminUser)
Write-Host ("  Server : {0}" -f $VEAdminServer)
Write-Host ""

# Stage the agent files in a fresh temp folder so a re-run never picks up
# stale leftovers from a previous attempt.
$Stage = Join-Path $env:TEMP ("VEAdminAgent-Setup-" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $Stage -Force | Out-Null
Write-Host ("Staging in {0}" -f $Stage)

foreach ($f in $Files) {
  $url  = "$VEAdminServer/install/agent/$f"
  $dest = Join-Path $Stage $f
  Write-Host ("  fetch {0}" -f $f)
  try {
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
  } catch {
    Write-Host ("Failed to download {0}: {1}" -f $f, $_.Exception.Message) -ForegroundColor Red
    exit 1
  }
}

# Hand off to install.ps1 with the pseudo and server URL pinned in.
# -NonInteractive so this runs cleanly when piped from iex (no TTY).
$Installer = Join-Path $Stage 'install.ps1'
Write-Host ""
Write-Host "Running installer..." -ForegroundColor Cyan
& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Installer \`
  -Username  $VEAdminUser \`
  -ServerUrl $VEAdminServer \`
  -NonInteractive

if ($LASTEXITCODE -ne 0) {
  Write-Host ("install.ps1 failed (exit {0}). Stage left at {1} for inspection." -f $LASTEXITCODE, $Stage) -ForegroundColor Red
  exit $LASTEXITCODE
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host ("  Installed. Agent will boot at next logon as '{0}'." -f $VEAdminUser) -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
`;
}
